### ISSUE TITLE
Carbon dependancy needs upgrade

### ISSUE THREAD

**Issue by rtrudel** [MDXDave/time-ago#2]
The plugin may prevent other plugins to work properly.

I had the issue with **Solspace Calendar** and it probably affect some other plugins which requires`^2.19` or so.

ex: Calendar's Carbon dependancy: `"nesbot/carbon": "^1.22.1|^2.19",`

To make it work again as a quick fix, I had to remove `time-ago` plugin and comment `|timeAgo` occurrences in my templates. I wish it can be fixed so I can reinstall it :)

Thank you.

**Comment by MDXDave** [comment]
Should be fixed in v1.1.0 (requires CraftCMS 4.x)
